name: Trigger Monorepo to Build Docs

on:
  push:
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  trigger_monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update-submodule workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/kuanchoulai10/monorepo/dispatches \
            -d '{"event_type":"update-submodules"}'